import Header from '@/components/Header/Header';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html lang="fr">
      <body>
        <Header />
        <div className="ml-72 ">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
